sudo: required
dist: trusty
language: generic # Force travis to use its minimal image with default Python settings
compiler:
  - gcc
env:
  matrix:
    - USE_DEB=true
      ROS_DISTRO="kinetic"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true
      ROS_DISTRO="kinetic"
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

install:
  - git clone https://github.com/davetcoleman/graph_msgs.git
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
